# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-07-02 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='live_link',
            field=models.CharField(default=3, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='repo_link',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
